//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberKarpNaz.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialService
    {
        public int Id { get; set; }
        public int IdService { get; set; }
        public Nullable<int> IdMaterial { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Service Service { get; set; }
    }
}
